### ISSUE TITLE
task setIssueField fails without useful explanation

### ISSUE THREAD

**Issue by Thomas-Bergmann** [IntershopCommunicationsAG/jiraconnector-gradle-plugin#24]
Caused by: com.intershop.gradle.jiraconnector.task.jira.UpdateVersionException: Version is null or empty! Please check your configuration.

> 02-Jun-2020 15:54:42 | at com.intershop.gradle.jiraconnector.task.jira.JiraConnector.updateVersions(JiraConnector.kt:450)
> 02-Jun-2020 15:54:42 | at com.intershop.gradle.jiraconnector.task.jira.JiraConnector.updateFixVersion(JiraConnector.kt:403)

**Comment by m-raab** [comment]
solved with latest release
